from .mountaincar.trainer import Trainer as MountainCarTrainer
from .mountaincar.trainer import DEFAULT_LOGGER_PROJECT_NAME as MOUNTAINCAR_DEFAULT_LOGGER_PROJECT_NAME 
from .mountaincar.trainer import DEFAULT_EXPERIMENT_NAME as MOUNTAINCAR_DEFAULT_EXPERIMENT_NAME 